[WIP]: Bounding Box for Selection
jupytercad/JupyterCAD pull request #473
Opened 2024-10-15 13:27 UTC by arjxn-py

2024-10-15 13:47 UTC, trungleduc commented on packages/base/src/3dview/mainview.tsx
> +          intersect.object.name === 'selectionBoundingBox'
Let's make `selectionBoundingBox` a constant variable

2024-10-15 13:52 UTC, trungleduc commented
holding CTRL and click on the object one more time creates a much bigger bounding box. 


https://github.com/user-attachments/assets/e6150fbb-2924-44aa-8383-73b2973f1042

2024-10-15 14:05 UTC, trungleduc commented
yeah, tested with the lasted preview link and it works well

2024-10-15 14:07 UTC, trungleduc commented
Thanks!

2024-10-15 14:13 UTC, arjxn-py commented
There's one more thing wrong related to the color update when changing color. Looks like I've removed something that wasn't meant to be.


https://github.com/user-attachments/assets/784b8a54-bee5-4c95-b33e-4ad9975c5120

2024-10-15 14:32 UTC, arjxn-py commented
> There's one more thing wrong related to the color update when changing color. Looks like I've removed something that wasn't meant to be.

Fixed.


https://github.com/user-attachments/assets/f7831e22-b4c9-4833-8662-4677400daa4e

2024-10-16 06:22 UTC, arjxn-py commented
Bot please update snapshots

2024-10-16 07:34 UTC, martinRenou requested changes
I still see a tiny issue, it seems there is still a place where we are setting the selected mesh color to `SELECTED_MESH_COLOR`. Because when I change the color to red, it's actually going to `SELECTED_MESH_COLOR` first.

Actually I would suggest getting rid of the `SELECTED_MESH_COLOR` as we won't be using it anymore. You could define your own constant `BOUNDING_BOXES_COLOR`.


https://github.com/user-attachments/assets/9421ffa8-2ded-425d-a29d-73f9a7a3c635

2024-10-16 11:09 UTC, arjxn-py commented
Done. Thanks @martinRenou


https://github.com/user-attachments/assets/97b4e025-789d-47b0-89d0-8c1dc01ad123

2024-10-16 11:41 UTC, martinRenou approved these changes
Thanks!

2024-10-16 11:41 UTC, merged